# =================================================================
# DROGUERIE JAMAL - RAILWAY DEPLOYMENT CONFIGURATION
# =================================================================

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacks]
builderImage = "ghcr.io/railwayapp/nixpacks:latest"

# Service configuration
[[services]]
name = "droguerie-backend"
source = "server"

[services.variables]
NODE_ENV = "production"
PORT = "${{RAILWAY_PORT}}"
DATABASE_TYPE = "sqlite"
FALLBACK_DATABASE_URL = "./database.sqlite"

# Build settings
[services.build]
command = "npm install && npm run seed:production"

# Health check
[services.healthcheck]
path = "/api/health"
interval = 30
